# Generated by Django 4.0 on 2022-01-09 14:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500, verbose_name='Tên bài viết')),
                ('slug', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Đường dẫn')),
                ('body', models.TextField(verbose_name='Nội dung')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '11. Bài viết',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500, verbose_name='Tên danh mục')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
            ],
            options={
                'verbose_name_plural': '10. Danh mục (Loại) sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='certifications', verbose_name='Hình ảnh')),
                ('photo_alt', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)')),
                ('is_display', models.BooleanField(default=False, verbose_name='Hiển thị trên trang chủ')),
            ],
            options={
                'verbose_name_plural': '08. Chứng nhận',
            },
        ),
        migrations.CreateModel(
            name='Effection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề')),
                ('content', models.TextField(blank=True, max_length=500, null=True, verbose_name='Công dụng')),
                ('group', models.CharField(choices=[('one', 'Nhóm 1'), ('two', 'Nhóm 2')], max_length=200, verbose_name='Nhóm')),
            ],
            options={
                'verbose_name_plural': '06. Công dụng',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề chính')),
                ('display_type', models.CharField(choices=[('left', 'Bên trái'), ('right', 'Bên phải')], max_length=200, verbose_name='Hiển thị')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên thành phần')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ingredients', verbose_name='Hình ảnh')),
                ('photo_alt', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)')),
            ],
            options={
                'verbose_name_plural': '05. Thành phần',
            },
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Tên Menu')),
                ('tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Menu Tag')),
                ('has_child_article_menu', models.BooleanField(default=False, verbose_name='Có chứa menu bài viết')),
            ],
            options={
                'verbose_name_plural': '01. Menu (Tiêu đề)',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Thứ tự')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Hình ảnh')),
                ('photo_alt', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)')),
            ],
            options={
                'verbose_name_plural': '07. Hình ảnh sản phẩm',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PropertyRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_top_left', models.ImageField(blank=True, null=True, upload_to='property_right', verbose_name='Hình ảnh (trên - trái)')),
                ('photo_top_left_alt', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)')),
                ('photo_top_right', models.ImageField(blank=True, null=True, upload_to='property_right', verbose_name='Hình ảnh (trên - phải)')),
                ('photo_top_right_alt', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề (Nguồn gốc sản phẩm)')),
                ('content', models.TextField(blank=True, max_length=700, null=True, verbose_name='Nội dung (Nguồn gốc sản phẩm)')),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='property_right', verbose_name='Hình ảnh chính')),
                ('photo_main_alt', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)')),
                ('title_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề (Nguồn gốc sản phẩm) (1)')),
                ('content_1', models.TextField(blank=True, max_length=700, null=True, verbose_name='Nội dung (Nguồn gốc sản phẩm) (1)')),
                ('photo_main_1', models.ImageField(blank=True, null=True, upload_to='property_right', verbose_name='Hình ảnh chính (1)')),
                ('photo_main_1_alt', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)')),
            ],
            options={
                'verbose_name_plural': '04. Nguồn gốc sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Báo cáo')),
                ('report_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='link')),
            ],
            options={
                'verbose_name_plural': '99. Xem báo cáo',
            },
        ),
        migrations.CreateModel(
            name='RetailProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên sản phẩm (bán lẻ)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='retail_products', verbose_name='Hình ảnh')),
                ('photo_alt', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)')),
            ],
            options={
                'verbose_name_plural': '09. Sản phẩm (Bán lẻ)',
            },
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiêu đề')),
                ('tags', models.TextField(verbose_name='Thẻ SEO')),
            ],
            options={
                'verbose_name_plural': '98. SEO',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tiêu đề (chung)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='slide', verbose_name='Hình ảnh slide')),
                ('photo_alt', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)')),
            ],
            options={
                'verbose_name_plural': '03. Slide hình ảnh',
            },
        ),
        migrations.CreateModel(
            name='WebContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('web_title', models.CharField(max_length=200, verbose_name='Tiêu đề trang web')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('company_name', models.CharField(max_length=500, verbose_name='Tên công ty')),
                ('address', models.TextField(max_length=500, verbose_name='Địa chỉ')),
                ('email', models.CharField(max_length=500, verbose_name='Email')),
                ('site_name', models.CharField(max_length=500, verbose_name='Tên website')),
                ('copy_right', models.CharField(max_length=200, verbose_name='Tên copyright')),
                ('banner_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nội dung banner 1')),
                ('banner_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nội dung banner 2')),
                ('banner_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nội dung banner 3')),
                ('banner_photo', models.ImageField(blank=True, null=True, upload_to='home_photos', verbose_name='Hình ảnh banner chính')),
                ('banner_photo_alt', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)')),
                ('counterfeiting', models.TextField(blank=True, max_length=500, null=True, verbose_name='Nội dung chống hàng giả')),
                ('counterfeiting_photo', models.ImageField(blank=True, null=True, upload_to='home_photos', verbose_name='Hình ảnh chống hàng giả')),
                ('counterfeiting_photo_alt', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)')),
                ('video_photo', models.ImageField(blank=True, null=True, upload_to='home_photos', verbose_name='Hình ảnh video')),
                ('video_photo_alt', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)')),
                ('effection_photo', models.ImageField(blank=True, null=True, upload_to='home_photos', verbose_name='Hình ảnh công dụng sản phẩm')),
                ('effection_photo_alt', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)')),
                ('effection_photo_1', models.ImageField(blank=True, null=True, upload_to='home_photos', verbose_name='Hình ảnh công dụng sản phẩm (1)')),
                ('effection_photo_1_alt', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)')),
                ('order_photo', models.ImageField(blank=True, null=True, upload_to='home_photos', verbose_name='Hình ảnh đặt hàng')),
                ('order_photo_alt', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)')),
            ],
            options={
                'verbose_name_plural': '02. Nội Dung Trang Web',
            },
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('youtube_embed_content', models.TextField(blank=True, null=True, verbose_name='Mã nhúng Youtube')),
            ],
            options={
                'verbose_name_plural': '15. Video Youtube',
            },
        ),
        migrations.CreateModel(
            name='ReleaseProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Tên (Đợt phát hành)')),
                ('product_quantity', models.IntegerField(verbose_name='Số lượng sản phẩm')),
                ('price', models.FloatField(verbose_name='Giá')),
                ('domain_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tên website')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diep_website.article', verbose_name='Bài viết')),
            ],
            options={
                'verbose_name_plural': '14. Tạo (Phát hành) Sản Phẩm',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_code', models.CharField(editable=False, max_length=100, null=True, verbose_name='Mã sản phẩm')),
                ('article_id', models.CharField(blank=True, editable=False, max_length=500, null=True, verbose_name='Mã bài viết')),
                ('product_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tên sản phẩm')),
                ('release_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tên (Đợt phát hành)')),
                ('product_price', models.FloatField(blank=True, null=True, verbose_name='Giá')),
                ('active_link', models.CharField(blank=True, editable=False, max_length=500, null=True, verbose_name='QRCode link')),
                ('serial_no', models.CharField(blank=True, editable=False, max_length=9, null=True)),
                ('scanned', models.BooleanField(default=False, verbose_name='Đã Scan')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diep_website.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name_plural': '12. Sản phẩm',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diep_website.category', verbose_name='Danh mục'),
        ),
    ]
