# Generated by Django 3.2.8 on 2021-12-21 01:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0932b53a-c5ee-4d5b-a482-b2bcc254d9b4'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('50611829-9e46-4a91-9f34-f6c5f07d5a18'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('product_code', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diep_website.category')),
            ],
        ),
    ]
