# Generated by Django 4.0 on 2022-01-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphoto',
            name='is_display',
            field=models.BooleanField(default=False, verbose_name='Hiển thị trang chủ'),
        ),
    ]
