# Generated by Django 4.0 on 2022-01-09 16:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0002_productphoto_is_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mã đơn hàng')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên khách hàng')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ghi chú')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('release_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diep_website.releaseproduct', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name_plural': '100. Xem đơn hàng',
                'ordering': ['-created'],
            },
        ),
    ]
