# Generated by Django 4.0 on 2022-01-10 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='release_product',
        ),
        migrations.AddField(
            model_name='order',
            name='retail_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diep_website.retailproduct', verbose_name='Sản phẩm bán lẻ'),
        ),
    ]
