# Generated by Django 3.2.4 on 2021-12-25 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0003_alter_article_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
