# Generated by Django 4.0 on 2022-01-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0004_remove_order_release_product_order_retail_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name_plural': '99. Xem đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name_plural': '98. Xem báo cáo'},
        ),
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name_plural': '97. SEO'},
        ),
        migrations.AddField(
            model_name='seo',
            name='group',
            field=models.CharField(choices=[('seo_home', 'SEO Trang chủ'), ('seo_article', 'SEO Bài viết')], default=2, max_length=200, verbose_name='Nhóm'),
            preserve_default=False,
        ),
    ]
