# Generated by Django 3.2.4 on 2021-12-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
