# Generated by Django 4.0 on 2021-12-27 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0006_alter_article_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
    ]
