# Generated by Django 4.0 on 2021-12-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0007_remove_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(),
        ),
    ]
