# Generated by Django 4.0 on 2021-12-27 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0009_label_releaselabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaselabel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
