# Generated by Django 4.0 on 2021-12-27 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0011_releaseproduct_delete_label_delete_releaselabel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
