# Generated by Django 4.0 on 2021-12-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0018_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productnew',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
