# Generated by Django 4.0 on 2021-12-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0022_alter_releaseproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
