# Generated by Django 4.0 on 2021-12-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0023_product_base_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_url',
        ),
    ]
