# Generated by Django 4.0 on 2021-12-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0024_remove_product_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='domain_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='releaseproduct',
            name='domain_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
