# Generated by Django 4.0 on 2021-12-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0025_product_domain_name_releaseproduct_domain_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='domain_name',
            new_name='active_link',
        ),
        migrations.AlterField(
            model_name='product',
            name='serial_no',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
