# Generated by Django 4.0 on 2021-12-28 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0027_product_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releaseproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='releaseproduct',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diep_website.article'),
        ),
    ]
