# Generated by Django 4.0 on 2022-01-01 10:34

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0029_remove_product_article_product_article_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
