# Generated by Django 4.0 on 2022-01-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0030_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
