# Generated by Django 4.0 on 2022-01-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0031_delete_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active_link',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='article_id',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='serial_no',
            field=models.CharField(blank=True, editable=False, max_length=9, null=True),
        ),
    ]
