# Generated by Django 4.0 on 2022-01-03 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0032_alter_product_active_link_alter_product_article_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Danh Mục Sản Phẩm'},
        ),
        migrations.AlterModelOptions(
            name='releaseproduct',
            options={'verbose_name_plural': 'Tạo (Phát hành) Sản Phẩm'},
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diep_website.category', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Tên danh mục'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article_id',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True, verbose_name='Mã bài viết'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diep_website.category', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(editable=False, max_length=100, null=True, verbose_name='Mã sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ngày phát hành'),
        ),
        migrations.AlterField(
            model_name='releaseproduct',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diep_website.article', verbose_name='Bài viết'),
        ),
        migrations.AlterField(
            model_name='releaseproduct',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='releaseproduct',
            name='domain_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tên website'),
        ),
        migrations.AlterField(
            model_name='releaseproduct',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='releaseproduct',
            name='price',
            field=models.FloatField(verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='releaseproduct',
            name='product_quantity',
            field=models.IntegerField(verbose_name='Số lượng sản phẩm'),
        ),
    ]
