# Generated by Django 4.0 on 2022-01-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0033_alter_category_options_alter_releaseproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Bài Viết'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Danh Mục'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Sản Phẩm'},
        ),
    ]
