# Generated by Django 4.0 on 2022-01-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0035_menu_webcontent_alter_product_active_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Menu Tag'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên Menu'),
        ),
    ]
