# Generated by Django 4.0 on 2022-01-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0036_menu_tag_alter_menu_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='MainMenu',
        ),
    ]
