# Generated by Django 4.0 on 2022-01-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0037_rename_menu_mainmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='has_child_article_menu',
            field=models.BooleanField(default=False, verbose_name='Có chứa menu bài viết'),
        ),
    ]
