# Generated by Django 4.0 on 2022-01-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0038_mainmenu_has_child_article_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('youtube_content', models.TextField(verbose_name='Nội dung youtube')),
            ],
            options={
                'verbose_name_plural': 'Video Youtube',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='release_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tên (Đợt phát hành)'),
        ),
        migrations.AlterField(
            model_name='releaseproduct',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên (Đợt phát hành)'),
        ),
        migrations.AlterField(
            model_name='webcontent',
            name='address',
            field=models.TextField(max_length=500, verbose_name='Địa chỉ'),
        ),
    ]
