# Generated by Django 4.0 on 2022-01-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0039_youtubevideo_alter_product_release_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='youtube_content',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='youtube_url',
            field=models.TextField(blank=True, null=True, verbose_name='Đường dẫn Youtube(URL)'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Tiêu đề'),
        ),
    ]
