# Generated by Django 4.0 on 2022-01-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0041_remove_youtubevideo_youtube_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tiêu đề (chung)')),
                ('image', models.ImageField(upload_to='images_upload/')),
            ],
            options={
                'verbose_name_plural': 'Slide hình ảnh',
            },
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề'),
        ),
    ]
