# Generated by Django 4.0 on 2022-01-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0042_slide_alter_youtubevideo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
        migrations.AddField(
            model_name='slide',
            name='image_slide',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hình ảnh slide'),
        ),
    ]
