# Generated by Django 4.0 on 2022-01-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0043_remove_slide_image_slide_image_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image_slide',
            field=models.ImageField(blank=True, null=True, upload_to='slide', verbose_name='Hình ảnh slide'),
        ),
    ]
