# Generated by Django 4.0 on 2022-01-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0044_alter_slide_image_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='image_slide',
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hình ảnh slide'),
        ),
    ]
