# Generated by Django 4.0 on 2022-01-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0045_remove_slide_image_slide_slide_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='image',
            new_name='photo',
        ),
    ]
