# Generated by Django 4.0 on 2022-01-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0047_alter_mainmenu_options_alter_webcontent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='slide', verbose_name='Hình ảnh slide'),
        ),
    ]
