# Generated by Django 4.0 on 2022-01-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0048_alter_slide_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='scanned',
            field=models.BooleanField(default=False, verbose_name='Đã Scan'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
    ]
