# Generated by Django 4.0 on 2022-01-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0049_report_product_scanned_product_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name_plural': '99. Xem báo cáo'},
        ),
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Xem báo cáo'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='link'),
        ),
    ]
