# Generated by Django 4.0 on 2022-01-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0050_alter_report_options_report_name_report_report_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_top_left', models.ImageField(blank=True, null=True, upload_to='property_right', verbose_name='Hình ảnh (trên - trái)')),
                ('photo_top_right', models.ImageField(blank=True, null=True, upload_to='property_right', verbose_name='Hình ảnh (trên - phải)')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề (Nguồn gốc sản phẩm)')),
                ('content', models.TextField(blank=True, max_length=700, null=True, verbose_name='Nội dung (Nguồn gốc sản phẩm)')),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='property_right', verbose_name='Hình ảnh chính')),
                ('title_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề (Nguồn gốc sản phẩm) (1)')),
                ('content_1', models.TextField(blank=True, max_length=700, null=True, verbose_name='Nội dung (Nguồn gốc sản phẩm) (1)')),
                ('photo_main_1', models.ImageField(blank=True, null=True, upload_to='property_right', verbose_name='Hình ảnh chính (1)')),
            ],
            options={
                'verbose_name_plural': '03. Nguồn gốc sản phẩm',
            },
        ),
        migrations.AddField(
            model_name='webcontent',
            name='banner_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nội dung banner 1'),
        ),
        migrations.AddField(
            model_name='webcontent',
            name='banner_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nội dung banner 2'),
        ),
        migrations.AddField(
            model_name='webcontent',
            name='banner_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nội dung banner 3'),
        ),
        migrations.AddField(
            model_name='webcontent',
            name='banner_photo',
            field=models.ImageField(blank=True, null=True, upload_to='home_photos', verbose_name='Hình ảnh banner chính'),
        ),
        migrations.AddField(
            model_name='webcontent',
            name='counterfeiting',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Nội dung chống hàng giả'),
        ),
        migrations.AddField(
            model_name='webcontent',
            name='counterfeiting_photo',
            field=models.ImageField(blank=True, null=True, upload_to='home_photos', verbose_name='Hình ảnh chống hàng giả'),
        ),
        migrations.AddField(
            model_name='webcontent',
            name='video_photo',
            field=models.ImageField(blank=True, null=True, upload_to='home_photos', verbose_name='Hình ảnh video'),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Báo cáo'),
        ),
        migrations.AlterField(
            model_name='webcontent',
            name='copy_right',
            field=models.CharField(max_length=200, verbose_name='Tên copyright'),
        ),
        migrations.AlterField(
            model_name='webcontent',
            name='web_title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề trang web'),
        ),
    ]
