# Generated by Django 4.0 on 2022-01-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0051_propertyright_webcontent_banner_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyright',
            name='photo_top_left',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='property_right', verbose_name='Hình ảnh (trên - trái)'),
        ),
        migrations.AlterField(
            model_name='propertyright',
            name='photo_top_right',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='property_right', verbose_name='Hình ảnh (trên - phải)'),
        ),
    ]
