# Generated by Django 4.0 on 2022-01-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0052_alter_propertyright_photo_top_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề chính')),
                ('display_type', models.CharField(choices=[('left', 'Bên trái'), ('right', 'Bên phải')], max_length=200, verbose_name='Hiển thị')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên thành phần')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ingredients', verbose_name='Hình ảnh')),
            ],
            options={
                'verbose_name_plural': '04. Thành phần',
            },
        ),
    ]
