# Generated by Django 4.0 on 2022-01-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0053_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Tên bài viết'),
        ),
    ]
