# Generated by Django 4.0 on 2022-01-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0054_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Hình ảnh')),
            ],
            options={
                'verbose_name_plural': '07. Chứng nhận',
            },
        ),
        migrations.CreateModel(
            name='Effection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề')),
                ('content', models.TextField(blank=True, max_length=500, null=True, verbose_name='Công dụng')),
                ('group', models.CharField(choices=[('one', 'Nhóm 1'), ('two', 'Nhóm 2')], max_length=200, verbose_name='Nhóm')),
            ],
            options={
                'verbose_name_plural': '05. Công dụng',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Thứ tự')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Hình ảnh')),
                ('alt', models.TextField(blank=True, max_length=500, null=True, verbose_name='Thẻ')),
            ],
            options={
                'verbose_name_plural': '06. Hình ảnh sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiêu đề')),
                ('tags', models.TextField(verbose_name='Thẻ SEO')),
            ],
            options={
                'verbose_name_plural': '98. SEO',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '09. Bài viết'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '08. Danh mục (Loại) sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '10. Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name_plural': '12. Slide hình ảnh'},
        ),
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'verbose_name_plural': '11. Video Youtube'},
        ),
        migrations.AddField(
            model_name='webcontent',
            name='effection_photo',
            field=models.ImageField(blank=True, null=True, upload_to='home_photos', verbose_name='Hình ảnh công dụng sản phẩm'),
        ),
        migrations.AddField(
            model_name='webcontent',
            name='effection_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='home_photos', verbose_name='Hình ảnh công dụng sản phẩm (1)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
    ]
