# Generated by Django 4.0 on 2022-01-06 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0055_certificate_effection_productphoto_seo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '10. Bài viết'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '09. Danh mục (Loại) sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name_plural': '08. Chứng nhận'},
        ),
        migrations.AlterModelOptions(
            name='effection',
            options={'verbose_name_plural': '06. Công dụng'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name_plural': '05. Thành phần'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '11. Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productphoto',
            options={'ordering': ['number'], 'verbose_name_plural': '07. Hình ảnh sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='propertyright',
            options={'verbose_name_plural': '04. Nguồn gốc sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='releaseproduct',
            options={'verbose_name_plural': '12. Tạo (Phát hành) Sản Phẩm'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name_plural': '03. Slide hình ảnh'},
        ),
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'verbose_name_plural': '14. Video Youtube'},
        ),
    ]
