# Generated by Django 4.0 on 2022-01-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0056_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên sản phẩm (bán lẻ)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Hình ảnh')),
            ],
            options={
                'verbose_name_plural': '09. Sản phẩm (Bán lẻ)',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '11. Bài viết'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '10. Danh mục (Loại) sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '12. Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='releaseproduct',
            options={'verbose_name_plural': '14. Tạo (Phát hành) Sản Phẩm'},
        ),
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'verbose_name_plural': '15. Video Youtube'},
        ),
    ]
