# Generated by Django 4.0 on 2022-01-07 04:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0057_retailproduct_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
