# Generated by Django 4.0 on 2022-01-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0058_alter_retailproduct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='retail_products', verbose_name='Hình ảnh'),
        ),
    ]
