# Generated by Django 4.0 on 2022-01-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0059_alter_retailproduct_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcontent',
            name='order_photo',
            field=models.ImageField(blank=True, null=True, upload_to='home_photos', verbose_name='Hình ảnh đặt hàng'),
        ),
    ]
