# Generated by Django 4.0 on 2022-01-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0060_webcontent_order_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Đường dẫn'),
        ),
    ]
