# Generated by Django 4.0 on 2022-01-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0061_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='alt',
        ),
        migrations.AddField(
            model_name='certificate',
            name='photo_alt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='photo_alt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='photo_alt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)'),
        ),
        migrations.AddField(
            model_name='propertyright',
            name='photo_main_1_alt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)'),
        ),
        migrations.AddField(
            model_name='propertyright',
            name='photo_main_alt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)'),
        ),
        migrations.AddField(
            model_name='propertyright',
            name='photo_top_left_alt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)'),
        ),
        migrations.AddField(
            model_name='propertyright',
            name='photo_top_right_alt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)'),
        ),
        migrations.AddField(
            model_name='retailproduct',
            name='photo_alt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)'),
        ),
        migrations.AddField(
            model_name='slide',
            name='photo_alt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)'),
        ),
        migrations.AddField(
            model_name='webcontent',
            name='banner_photo_alt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)'),
        ),
        migrations.AddField(
            model_name='webcontent',
            name='counterfeiting_photo_alt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)'),
        ),
        migrations.AddField(
            model_name='webcontent',
            name='effection_photo_1_alt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)'),
        ),
        migrations.AddField(
            model_name='webcontent',
            name='effection_photo_alt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)'),
        ),
        migrations.AddField(
            model_name='webcontent',
            name='order_photo_alt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)'),
        ),
        migrations.AddField(
            model_name='webcontent',
            name='video_photo_alt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả ngắn (Hình ảnh)'),
        ),
        migrations.AlterField(
            model_name='propertyright',
            name='photo_top_left',
            field=models.ImageField(blank=True, null=True, upload_to='property_right', verbose_name='Hình ảnh (trên - trái)'),
        ),
        migrations.AlterField(
            model_name='propertyright',
            name='photo_top_right',
            field=models.ImageField(blank=True, null=True, upload_to='property_right', verbose_name='Hình ảnh (trên - phải)'),
        ),
    ]
