# Generated by Django 4.0 on 2022-01-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diep_website', '0062_remove_productphoto_alt_certificate_photo_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='certifications', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='link'),
        ),
    ]
